/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthConnexionRouteImport } from './routes/auth/connexion'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as PublicProduitsRouteImport } from './routes/_public/produits'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as AdminPromotionsIndexRouteImport } from './routes/admin/promotions/index'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin/produits/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPromotionsNewRouteImport } from './routes/admin/promotions/new'
import { Route as AdminProduitsNewRouteImport } from './routes/admin/produits/new'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories/new'
import { Route as AdminPromotionsIdEditRouteImport } from './routes/admin/promotions/$id.edit'
import { Route as AdminProduitsIdEditRouteImport } from './routes/admin/produits/$id.edit'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin/categories/$id.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/auth/connexion',
  path: '/auth/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const PublicProduitsRoute = PublicProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const AdminPromotionsIndexRoute = AdminPromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsNewRoute = AdminPromotionsNewRouteImport.update({
  id: '/promotions/new',
  path: '/promotions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsNewRoute = AdminProduitsNewRouteImport.update({
  id: '/produits/new',
  path: '/produits/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsIdEditRoute = AdminPromotionsIdEditRouteImport.update({
  id: '/promotions/$id/edit',
  path: '/promotions/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsIdEditRoute = AdminProduitsIdEditRouteImport.update({
  id: '/produits/$id/edit',
  path: '/produits/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/categories/$id/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/produits': typeof PublicProduitsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/produits/new': typeof AdminProduitsNewRoute
  '/admin/promotions/new': typeof AdminPromotionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/admin/promotions': typeof AdminPromotionsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/produits/$id/edit': typeof AdminProduitsIdEditRoute
  '/admin/promotions/$id/edit': typeof AdminPromotionsIdEditRoute
}
export interface FileRoutesByTo {
  '/contact': typeof PublicContactRoute
  '/produits': typeof PublicProduitsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/produits/new': typeof AdminProduitsNewRoute
  '/admin/promotions/new': typeof AdminPromotionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/admin/promotions': typeof AdminPromotionsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/produits/$id/edit': typeof AdminProduitsIdEditRoute
  '/admin/promotions/$id/edit': typeof AdminPromotionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/produits': typeof PublicProduitsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/produits/new': typeof AdminProduitsNewRoute
  '/admin/promotions/new': typeof AdminPromotionsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/admin/promotions/': typeof AdminPromotionsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/produits/$id/edit': typeof AdminProduitsIdEditRoute
  '/admin/promotions/$id/edit': typeof AdminPromotionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/contact'
    | '/produits'
    | '/admin/parametres'
    | '/auth/connexion'
    | '/'
    | '/admin/'
    | '/admin/categories/new'
    | '/admin/produits/new'
    | '/admin/promotions/new'
    | '/api/auth/$'
    | '/admin/categories'
    | '/admin/produits'
    | '/admin/promotions'
    | '/admin/categories/$id/edit'
    | '/admin/produits/$id/edit'
    | '/admin/promotions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/produits'
    | '/admin/parametres'
    | '/auth/connexion'
    | '/'
    | '/admin'
    | '/admin/categories/new'
    | '/admin/produits/new'
    | '/admin/promotions/new'
    | '/api/auth/$'
    | '/admin/categories'
    | '/admin/produits'
    | '/admin/promotions'
    | '/admin/categories/$id/edit'
    | '/admin/produits/$id/edit'
    | '/admin/promotions/$id/edit'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/contact'
    | '/_public/produits'
    | '/admin/parametres'
    | '/auth/connexion'
    | '/_public/'
    | '/admin/'
    | '/admin/categories/new'
    | '/admin/produits/new'
    | '/admin/promotions/new'
    | '/api/auth/$'
    | '/admin/categories/'
    | '/admin/produits/'
    | '/admin/promotions/'
    | '/admin/categories/$id/edit'
    | '/admin/produits/$id/edit'
    | '/admin/promotions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthConnexionRoute: typeof AuthConnexionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/connexion': {
      id: '/auth/connexion'
      path: '/auth/connexion'
      fullPath: '/auth/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/produits': {
      id: '/_public/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof PublicProduitsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/promotions/': {
      id: '/admin/promotions/'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions/new': {
      id: '/admin/promotions/new'
      path: '/promotions/new'
      fullPath: '/admin/promotions/new'
      preLoaderRoute: typeof AdminPromotionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/new': {
      id: '/admin/produits/new'
      path: '/produits/new'
      fullPath: '/admin/produits/new'
      preLoaderRoute: typeof AdminProduitsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions/$id/edit': {
      id: '/admin/promotions/$id/edit'
      path: '/promotions/$id/edit'
      fullPath: '/admin/promotions/$id/edit'
      preLoaderRoute: typeof AdminPromotionsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/$id/edit': {
      id: '/admin/produits/$id/edit'
      path: '/produits/$id/edit'
      fullPath: '/admin/produits/$id/edit'
      preLoaderRoute: typeof AdminProduitsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicProduitsRoute: typeof PublicProduitsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicProduitsRoute: PublicProduitsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminParametresRoute: typeof AdminParametresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminProduitsNewRoute: typeof AdminProduitsNewRoute
  AdminPromotionsNewRoute: typeof AdminPromotionsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
  AdminPromotionsIndexRoute: typeof AdminPromotionsIndexRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
  AdminProduitsIdEditRoute: typeof AdminProduitsIdEditRoute
  AdminPromotionsIdEditRoute: typeof AdminPromotionsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminParametresRoute: AdminParametresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminProduitsNewRoute: AdminProduitsNewRoute,
  AdminPromotionsNewRoute: AdminPromotionsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
  AdminPromotionsIndexRoute: AdminPromotionsIndexRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
  AdminProduitsIdEditRoute: AdminProduitsIdEditRoute,
  AdminPromotionsIdEditRoute: AdminPromotionsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthConnexionRoute: AuthConnexionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
